Completed Works Section & About Myself Section
CVILLA09/Microverse-Portfolio-Project pull request #4
Opened 2023-06-08 20:55 UTC by CVILLA09

This pull request includes the completed mobile version of the portfolio section. I have implemented the "Works" section and the "About myself" section as per the project requirements. The content is aligned using flexbox and CSS Grid combined. I have also ensured that the website is responsive and follows the specified breakpoints. The design has been closely matched to the Figma template provided. Please review and confirm in order to merge the changes into the main branch.

2023-06-08 21:46 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @CVILLA09 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Understand how to parse a Figma design to create a UI.
- ✔️ Use Flexbox to place elements in the page.
- ✔️ Use CSS Grid to place elements in the page.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 21:46 UTC, abdulhamiid commented on index.html
> +    </article>
According to the[ project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md), kindly use `Flexbox` to lay out an individual card. 😊🛠

* This gives us a lot of options to align all our elements, plus, it's responsive.

2023-06-08 21:46 UTC, abdulhamiid commented on index.html
> +        <h2>Tonic</h2>
To ensure that we stick to stick to the design as much as possible, let's use the same color for the title as Figma 👍😎

Your design
![image](https://github.com/CVILLA09/Portfolio/assets/78251927/4330145e-106b-4235-a94b-2a2f0bdbec4b)

Figma
![image](https://github.com/CVILLA09/Portfolio/assets/78251927/5c4efbe3-719f-4d4d-b803-651cd5f50111)

2023-06-08 21:46 UTC, abdulhamiid commented on index.html
> +   <section id="about-section" class="about-section">
Please use `Flexbox` to align the content of the "About myself" section as stated in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md), 👍🛠

2023-06-08 21:46 UTC, abdulhamiid commented on index.html
> +            </ul>
According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md), please use `ul` and `li` for categories in "About myself" section. i.e. `Languages`, `Frameworks`, and `Skills` should be list items.


Example
```HTML
<ul>
  <li>
    <h3>Languages</h3>
    . . . 
    <ul>
       <li>JavaScript</li>
       <li> . . .  </li>
       <li> . . .  </li>
    </ul>
  </li>
  <li>
    <h3>Frameworks</h3>
     . . . 
  </li>
  <li> 
   <h3>Skills</h3>
    . . . 
  </li>
</ul>
```

Kindly note that the category items are wrapped in a single `ul` tag 👀🤗

2023-06-08 21:46 UTC, abdulhamiid commented on style.css
> +}
Your design
![image](https://github.com/CVILLA09/Portfolio/assets/78251927/81fb72f7-0edb-40f1-8f8a-b6d5e8c1d74e)

Figma
![image](https://github.com/CVILLA09/Portfolio/assets/78251927/7f85bc4e-9455-4f57-8d9a-47e6a7fb2a7e)

I would suggest that we use pixels to enable a smooth border-radius similar to the design in Figma. 🤓

example
```CSS
border-radius: 0 80px 0 0;
```

2023-06-09 23:16 UTC, frempongdev requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @CVILLA09   👋🏼 
I'm Frempong.

You've done a great job implementing most of the requirements for this project 🚀, but there are a few changes I recommend be made. You're almost done, keep up the good work! 🤖 🎆 

<img src="https://media.giphy.com/media/KG5KpLlr1UEPvwgkiM/giphy-downsized.gif"/>

 ## Highlights
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Kindly Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 23:16 UTC, frempongdev commented on index.html
> +          </ul>
- [ ] As pointed out by your earlier reviewer, please make sure that all the technology categories (`"Languages"`, `"Frameworks"` and `"Skills"`) are in a `<ul>`, each of them in a `<li>` 🦭 

Kindly follow the guidelines below provided by the earlier reviewer 🎯 

![image](https://github.com/CVILLA09/Portfolio/assets/117144028/4292ade2-0816-437c-a4c7-caefe27d3235)

From the above, each technology section gets its own `<li>` and are all found inside one `<ul>`
The technologies can also make use of sub `<ul>'s` and `<li>'s` to make their own sub-lists 🪜 

Hence
**The technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`**

2023-06-09 23:16 UTC, frempongdev commented on style.css
> +  display: flex;
[OPTIONAL]
- [ ] Good job using `display: flex;` in the main container for the project cards, however the project requirement is to use a `display: grid` for the main container of the work section. ↔️ 👍🏿

2023-06-10 18:09 UTC, Efiamotu-1 approved these changes
Hi @CVILLA09 . 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PRItle & summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 18:09 UTC, Efiamotu-1 commented on index.html
> +               </div>
[OPTIONAL]
- [ ] The `div` in this highlighted line is not properly placed as an enclosing closing tag. kindly fix this for better html structure before merging :+1: :sparkles:

2023-06-11 01:46 UTC, merged