Pair program - Add Contact Form
CVILLA09/Microverse-Portfolio-Project pull request #5
Opened 2023-06-14 18:20 UTC by CVILLA09

Description:

This pull request introduces the following changes to the Portfolio project:

Contact Form: A new contact form has been added to the portfolio. This form includes fields for name, email, and message. Each field has specific validation rules as per the project requirements. The form uses the Formspree service to collect the data.

Mobile Version: The portfolio has been made responsive to accommodate mobile devices. The design follows the provided Figma template and uses flexbox for layout. The website is responsive for screen sizes of 375px (mobile) and 768px (desktop).

Code Quality: The code has been checked for linter errors and follows the correct GitHub flow. The work has been documented in a professional way.

Please review these changes and provide your feedback.

2023-06-14 18:23 UTC, CVILLA09 commented
<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

2023-06-14 18:56 UTC, usorfaitheloho requested changes
> Hi @CVILLA09  ,
> 
> Great job for implementing some of the Project Requirements, but there are some changes that need to be implemented in order to proceed to the next project 👍
> 
> ## Highlights 👏🏻
> ✔️ Good design implementation ✔️ You used the correct Git Hub-Flow. ✔️ Good README 
> 
> ![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif) 

> ## Required Changes ♻️
> _Check the comments below the review._

> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 18:56 UTC, usorfaitheloho commented on style.css
> +}
You did well  implementing the project requirement, please implement the following design changes so you'd have a better UI and better user interaction :

-  kindly include the background images for this contact form section to have a really pleasant form suitable for users' aesthetics
- kindly add the placeholder colors implement in the Figma design template
-  please adjust the submit button to be in the same margin as the other input just as it is in the design given
- kindly use the right font-color for the hover property of your button so it looks similar to the design we have 😄 

Your design :
![image](https://github.com/CVILLA09/Portfolio/assets/20537712/ed0ba382-2a10-4989-8c6c-06af4cc9ab4b)

Figma design :
![image](https://github.com/CVILLA09/Portfolio/assets/20537712/43f852b5-c4da-4f0e-9b87-11aec26a0ec1)

2023-06-14 20:06 UTC, Cabraham1 approved these changes
Hi @CVILLA09  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 21:05 UTC, merged

2023-06-15 14:25 UTC, CVILLA09 commented
<img src="https://media3.giphy.com/media/nFFguNjdeotwc/giphy.gif"/>

2023-06-15 14:27 UTC, fmalgarini commented
Hi @CVILLA09 👋 , 

Your project is complete! 👏👏  There is nothing else to say other than... it's time to merge it 
🎉 Congratulations! 🎉 


## Highlights
📌 Fixed all isues that you reviewer suggest you to do✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅


## Optional suggestions

[ ] I suggest you to merge this branch  to the main and delete this. Just for stay more organized for the next project. 😀😀 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 14:47 UTC, fmalgarini commented
Hi @CVILLA09 👋 , 

Your project is complete! 👏👏  There is nothing else to say other than... it's time to merge it 
🎉 Congratulations! 🎉 


## Highlights
📌 Fixed all isues that you reviewer suggest you to do✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

<img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDg1dms2cjU2NGNjZnphdWNuaXdrczRkNGRjbnRqeTE2dnk3anhtdiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/XreQmk7ETCak0/giphy.gif"/>

## Optional suggestions

[ ] I suggest you to merge this branch  to the main and delete this. Just for stay more organized for the next project. 😀😀 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._